name: CI

on: [push, pull_request]

permissions: read-all

env:
  OCAML_VERSION: 4.14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install OCaml ${{env.OCAML_VERSION}}
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: ${{env.OCAML_VERSION}}
        dune-cache: true

    - name: Build dependencies
      if: steps.cache.outputs.cache-hit != 'true' 
      run: |
        opam repo add coq-released https://coq.inria.fr/opam/released
        opam pin -y coq-equations "https://github.com/mattam82/Coq-Equations.git#8.18"
        opam pin -y coq-metacoq-common "https://github.com/MetaCoq/metacoq.git#efe2b96"
        opam pin -y coq-metacoq-utils "https://github.com/MetaCoq/metacoq.git#efe2b96"
        opam pin -y coq-metacoq-template "https://github.com/MetaCoq/metacoq.git#efe2b96"
        opam install . --deps-only --with-doc --with-test
        opam list --installed

    - name: Build interfaces (vos)
      run: opam exec -- make -j 2 vos TIMED=1

    - name: Build full (vo)
      run: opam exec -- make -j 2 all TIMED=1
